[workspace]

resolver = "2"

default-members = ["tests"]
members = ["netrun", "tests"]


[workspace.dependencies]
anyhow = "~1.0"
tokio = { version = "~1.48", features = ["full"] }
tarpc = { version = "~0.37", features = ["full"] }
serde = "~1.0"
serde_json = "~1.0"
log = "~0.4"
futures = "~0.3"

netrun = { path = "netrun" }
